#!/usr/bin/env python3
"""Keep the gallery manifests, their thumbnails and the markup in agreement.

The home page gallery used to be nineteen hand-written <button> elements
pointing straight at full-resolution originals -- so the grid downloaded
7.65 MB of images to display thumbnails. This tool owns that markup now.

There are two collections, each with its own manifest and its own page:

  gallery.yml      curated event photos -> the grid and hero slides on
                   index.html
  submissions.yml  whatever members have sent in through the upload form ->
                   the sideways rail on submit.html, which carries the
                   submitter's credit, caption and date into the lightbox

  sync   rebuild thumbnails, hero slides and the generated markup between
         the gallery:start / gallery:end, hero:start / hero:end and
         submissions:start / submissions:end markers
  add    take one or more newly supplied photos, derive a web-sized original
         and a thumbnail, append manifest entries, then sync
  check  verify each manifest, the thumbnails and the markup all agree; exits
         non-zero on any drift, so CI can catch a photo added by hand

The tool only ever *appends* to a manifest, so comments and hand-written
notes in it survive. It never rewrites a file wholesale.

Requires PyYAML and Pillow.
"""

from __future__ import annotations

import argparse
import datetime
import html
import json
import pathlib
import re
import sys

import yaml
from PIL import Image, ImageOps

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "data" / "gallery.yml"
# Submitted photos live in the same directory and come out of the same
# processing as the curated ones; what separates them is the manifest they are
# listed in, and therefore which page they appear on.
SUBMISSION_MANIFEST = ROOT / "assets" / "data" / "submissions.yml"
PHOTOS = ROOT / "assets" / "img" / "events"
THUMBS = PHOTOS / "thumbs"
SLIDES = ROOT / "assets" / "img" / "hero-slides"
INDEX = ROOT / "index.html"
SUBMIT = ROOT / "submit.html"
# Deliberately not committed: the whole repository is published by GitHub
# Pages, so anything tracked here would be public. See README.
CONTACTS = ROOT / "submissions" / "contacts.yml"

START = "<!-- gallery:start -- generated by tools/gallery.py; do not edit by hand -->"
END = "<!-- gallery:end -->"
# The home page hero band crossfades through the gallery photos. Its markup
# is generated from the same manifest into its own markers.
HERO_START = "<!-- hero:start -- generated by tools/gallery.py; do not edit by hand -->"
HERO_END = "<!-- hero:end -->"
# The submit page's own gallery: what members have sent in, kept off the home
# page so that it stays curated.
RAIL_START = "<!-- submissions:start -- generated by tools/gallery.py; do not edit by hand -->"
RAIL_END = "<!-- submissions:end -->"
# Shown inside the rail markers while nothing has been submitted yet.
RAIL_EMPTY = (
    '<p class="rail__empty">Nothing has been sent in yet &mdash; yours could be '
    "the first. Use the button above to add your photos to this gallery.</p>"
)

THUMB_EDGE = 480
THUMB_QUALITY = 78
FULL_EDGE = 1600
FULL_QUALITY = 82
SLIDE_EDGE = 1280
SLIDE_QUALITY = 80
INDENT = " " * 8
HERO_INDENT = " " * 4


# ---------------------------------------------------------------- manifest --


def load(path: pathlib.Path = MANIFEST) -> list[dict]:
    if not path.exists():
        sys.exit(f"missing manifest: {path.relative_to(ROOT)}")
    data = yaml.safe_load(path.read_text()) or {}
    photos = data.get("photos") or []
    if not isinstance(photos, list):
        sys.exit(f"{path.name}: 'photos' must be a list")
    for entry in photos:
        if not isinstance(entry, dict) or not entry.get("file"):
            sys.exit(f"{path.name}: every entry needs a 'file' key (got {entry!r})")
    return photos


def append(entries: list[dict], path: pathlib.Path = MANIFEST) -> None:
    """Append entries as text so existing comments and ordering survive."""
    out = []
    for entry in entries:
        out.append(f"  - file: {json.dumps(entry['file'], ensure_ascii=False)}")
        out.append(f"    alt: {json.dumps(entry['alt'], ensure_ascii=False)}")
        for key in ("credit", "caption", "date"):
            if entry.get(key):
                out.append(f"    {key}: {json.dumps(entry[key], ensure_ascii=False)}")
    text = path.read_text()
    if not text.endswith("\n"):
        text += "\n"
    # Appended entries are a block sequence, which an empty list written as
    # `photos: []` cannot take -- the file would stop parsing. Rewrite that
    # one form in passing, so the first append works whatever the manifest
    # looked like before it.
    text = re.sub(r"^photos:\s*\[\s*\]\s*$", "photos:", text, count=1, flags=re.MULTILINE)
    path.write_text(text + "\n".join(out) + "\n")


def remember_contact(name: str, email: str, files: list[str]) -> None:
    CONTACTS.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "date": datetime.date.today().isoformat(),
        "name": name,
        "email": email,
        "files": files,
    }
    with CONTACTS.open("a") as handle:
        handle.write(yaml.safe_dump([record], sort_keys=False, allow_unicode=True))


# -------------------------------------------------------------- derivatives --


def derive(src: pathlib.Path, dst: pathlib.Path, edge: int, quality: int) -> None:
    """Write a bounded, metadata-free copy of src to dst.

    Re-encoding through a fresh image drops ALL metadata, which is the point:
    phone photos carry GPS coordinates and we do not want to publish those.
    exif_transpose applies the orientation tag first so portrait shots do not
    come out sideways once that tag is gone.
    """
    with Image.open(src) as im:
        im = ImageOps.exif_transpose(im)
        im = im.convert("RGB")
        im.thumbnail((edge, edge * 4), Image.LANCZOS)
        dst.parent.mkdir(parents=True, exist_ok=True)
        im.save(dst, "JPEG", quality=quality, optimize=True, progressive=True)


def thumb_path(name: str) -> pathlib.Path:
    return THUMBS / (pathlib.Path(name).stem + ".jpg")


def slide_path(name: str) -> pathlib.Path:
    return SLIDES / (pathlib.Path(name).stem + ".jpg")


# ----------------------------------------------------------------- markup --


def attr(value) -> str:
    """An attribute value, safely quoted.

    Captions and credits are written by members rather than by us, so they are
    the one thing in the generated markup that cannot be assumed markup-free.
    Newlines and runs of spaces are collapsed too: a caption is a sentence,
    not a layout.
    """
    return html.escape(" ".join(str(value or "").split()), quote=True)


def render(photos: list[dict]) -> str:
    lines = []
    for entry in photos:
        name = entry["file"]
        src = f"assets/img/events/thumbs/{pathlib.Path(name).stem}.jpg"
        full = f"assets/img/events/{name}"
        lines.append(
            f'{INDENT}<button type="button">'
            f'<img src="{src}" data-full="{attr(full)}"'
            f' alt="{attr(entry.get("alt", ""))}"></button>'
        )
    return "\n".join(lines)


def render_rail(photos: list[dict]) -> str:
    """The submit page's own gallery: one button per submitted photo.

    Each button carries the submission's details as data attributes, which is
    what the lightbox reads to show who sent the photo and what they said
    about it. Nothing is served for them separately -- the details travel with
    the image they belong to.
    """
    if not photos:
        return INDENT + RAIL_EMPTY
    lines = []
    for entry in photos:
        stem = pathlib.Path(entry["file"]).stem
        src = f"assets/img/events/thumbs/{stem}.jpg"
        full = f"assets/img/events/{entry['file']}"
        bits = [f'src="{attr(src)}"', f'data-full="{attr(full)}"']
        for key in ("credit", "caption", "date"):
            if entry.get(key):
                bits.append(f'data-{key}="{attr(entry[key])}"')
        bits.append(f'alt="{attr(entry.get("alt", ""))}"')
        lines.append(
            f'{INDENT}<button type="button" class="rail__item">'
            f'<img {" ".join(bits)}></button>'
        )
    return "\n".join(lines)


def splice(index_text: str, body: str, start: str = START, end: str = END,
           indent: str = INDENT) -> str:
    pattern = re.compile(
        re.escape(start) + r".*?" + re.escape(end), re.DOTALL
    )
    if not pattern.search(index_text):
        sys.exit(
            "the page is missing the markers this markup is generated into --\n"
            f"expected to find both of:\n  {start}\n  {end}"
        )
    replacement = f"{start}\n{body}\n{indent}{end}"
    return pattern.sub(lambda _: replacement, index_text, count=1)


# ------------------------------------------------------------------- hero --


def render_hero(photos: list[dict]) -> str:
    """The hero band's crossfading slides: one <figure> per gallery photo.

    Slides reuse the 480 px grid thumbnails on small screens via srcset and
    load a 1280 px derivative the rest of the time. Only the first slide is
    eager; the rest are lazy, so nothing above the fold waits on them and
    the show pulls images one at a time as it advances. The first figure
    carries is-current in the markup, which is what a no-JS visitor sees.
    """
    lines = []
    for i, entry in enumerate(photos):
        stem = pathlib.Path(entry["file"]).stem
        slide = f"assets/img/hero-slides/{stem}.jpg"
        thumb = f"assets/img/events/thumbs/{stem}.jpg"
        alt = entry.get("alt", "")
        loading = "eager" if i == 0 else "lazy"
        current = " is-current" if i == 0 else ""
        lines.append(
            f'{HERO_INDENT}<figure class="hero__slide{current}">'
            f'<img src="{slide}" srcset="{thumb} 480w, {slide} 1280w"'
            f' sizes="100vw" loading="{loading}" alt="{alt}"></figure>'
        )
    return "\n".join(lines)


def splice_hero(index_text: str, body: str) -> str:
    return splice(index_text, body, HERO_START, HERO_END, HERO_INDENT)


def splice_rail(submit_text: str, body: str) -> str:
    return splice(submit_text, body, RAIL_START, RAIL_END)


# ---------------------------------------------------------------- commands --


def refresh(entry: dict, *, slides: bool, force: bool = False) -> None:
    """Re-derive the sizes this photo needs, where a derivative is stale."""
    src = PHOTOS / entry["file"]
    if not src.exists():
        sys.exit(f"manifest lists a missing photo: {src.relative_to(ROOT)}")
    wanted = [(thumb_path(entry["file"]), THUMB_EDGE, THUMB_QUALITY)]
    if slides:
        wanted.append((slide_path(entry["file"]), SLIDE_EDGE, SLIDE_QUALITY))
    for dst, edge, quality in wanted:
        if force or not dst.exists() or dst.stat().st_mtime < src.stat().st_mtime:
            derive(src, dst, edge, quality)


def cmd_sync(args) -> int:
    curated = load()
    sent_in = load(SUBMISSION_MANIFEST)
    for entry in curated:
        refresh(entry, slides=True, force=args.force)
    for entry in sent_in:
        # Submitted photos are not on the home page, so they get no hero slide.
        refresh(entry, slides=False, force=args.force)

    index = INDEX.read_text()
    index = splice(index, render(curated))
    index = splice_hero(index, render_hero(curated))
    INDEX.write_text(index)

    submit = SUBMIT.read_text()
    SUBMIT.write_text(splice_rail(submit, render_rail(sent_in)))

    print(f"  {len(curated)} home-page photos  ->  thumbs, hero slides + index.html markup")
    print(f"  {len(sent_in)} submitted photos  ->  thumbs + submit.html markup")
    return 0


def add_photos(
    files,
    *,
    alt: str,
    credit: str,
    date: str,
    caption: str = "",
    collection: str = "gallery",
) -> list[dict]:
    """Derive web-sized copies, append manifest entries and sync.

    Shared by the `add` command and by tools/publish_submissions.py, which is
    what the publishing Action runs -- so a queued submission and a photo
    added by hand go through identical processing. `collection` decides which
    manifest the entries land in, and therefore which page shows them; the
    file numbering is shared, so a photo only ever has one name.
    """
    to_submissions = collection == "submissions"
    manifest = SUBMISSION_MANIFEST if to_submissions else MANIFEST
    used = {entry["file"] for entry in load() + load(SUBMISSION_MANIFEST)}
    numbers = [
        int(p.stem) for p in PHOTOS.iterdir()
        if p.is_file() and p.stem.isdigit()
    ]
    nxt = max(numbers, default=0)
    added: list[dict] = []

    for raw in files:
        src = pathlib.Path(raw).expanduser()
        if not src.exists():
            raise SystemExit(f"no such file: {src}")
        nxt += 1
        name = f"{nxt:02d}.jpg"
        while name in used:
            nxt += 1
            name = f"{nxt:02d}.jpg"
        used.add(name)
        dst = PHOTOS / name
        derive(src, dst, FULL_EDGE, FULL_QUALITY)
        if not to_submissions:
            derive(src, slide_path(name), SLIDE_EDGE, SLIDE_QUALITY)
        added.append(
            {
                "file": name,
                "alt": alt,
                "credit": credit,
                "caption": caption,
                "date": date,
            }
        )
        before = src.stat().st_size
        after = dst.stat().st_size
        print(
            f"  {src.name}  ->  {dst.relative_to(ROOT)}"
            f"  ({before / 1048576:.2f} MB -> {after / 1048576:.2f} MB, EXIF stripped)"
        )

    append(added, manifest)
    cmd_sync(argparse.Namespace(force=False))
    return added


def cmd_add(args) -> int:
    added = add_photos(
        args.files,
        alt=args.alt,
        credit=args.credit,
        date=args.date,
        caption=args.caption,
        collection=args.collection,
    )
    if args.email:
        remember_contact(args.name or args.credit, args.email, [e["file"] for e in added])
        print(f"  contact recorded in {CONTACTS.relative_to(ROOT)} (not committed)")
    return 0


def collection_problems(entry: dict, *, slides: bool) -> list[str]:
    name = entry["file"]
    problems = []
    if not (PHOTOS / name).exists():
        problems.append(f"manifest lists a missing photo: {name}")
    if not thumb_path(name).exists():
        problems.append(f"missing thumbnail for {name} (run: gallery.py sync)")
    if slides and not slide_path(name).exists():
        problems.append(f"missing hero slide for {name} (run: gallery.py sync)")
    return problems


def cmd_check(args) -> int:
    curated = load()
    sent_in = load(SUBMISSION_MANIFEST)
    problems: list[str] = []

    for entry in curated:
        problems.extend(collection_problems(entry, slides=True))
    for entry in sent_in:
        problems.extend(collection_problems(entry, slides=False))

    on_disk = {
        p.name for p in PHOTOS.iterdir()
        if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}
    }
    listed = {e["file"] for e in curated} | {e["file"] for e in sent_in}
    for name in sorted(on_disk - listed):
        problems.append(f"{name} is in assets/img/events/ but in neither manifest")
    for name in sorted({e["file"] for e in curated} & {e["file"] for e in sent_in}):
        problems.append(f"{name} is listed in both manifests")

    index_text = INDEX.read_text()
    expected = splice(index_text, render(curated))
    expected = splice_hero(expected, render_hero(curated))
    if expected != index_text:
        problems.append("index.html generated markup is out of date (run: gallery.py sync)")

    submit_text = SUBMIT.read_text()
    if splice_rail(submit_text, render_rail(sent_in)) != submit_text:
        problems.append("submit.html generated markup is out of date (run: gallery.py sync)")

    for problem in problems:
        print(f"  FAIL  {problem}")
    if problems:
        print(f"\n{len(problems)} problem(s)")
        return 1
    print(
        f"  OK  {len(curated)} home-page photos and {len(sent_in)} submitted, "
        "thumbs present, markup in sync"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_sync = sub.add_parser("sync", help="rebuild thumbs and markup from the manifest")
    p_sync.add_argument("--force", action="store_true", help="rebuild every thumb")
    p_sync.set_defaults(func=cmd_sync)

    p_add = sub.add_parser("add", help="add newly supplied photos and publish them")
    p_add.add_argument("files", nargs="+")
    p_add.add_argument("--alt", default="Photo from a previous SUAS event")
    p_add.add_argument("--credit", default="")
    p_add.add_argument("--caption", default="", help="shown with the photo on submit.html")
    p_add.add_argument(
        "--collection",
        choices=("gallery", "submissions"),
        default="gallery",
        help="which manifest and page the photos belong to",
    )
    p_add.add_argument("--date", default=datetime.date.today().isoformat())
    p_add.add_argument("--name", default="", help="submitter's name, for the contact log")
    p_add.add_argument("--email", default="", help="submitter's email, for the contact log")
    p_add.set_defaults(func=cmd_add)

    p_check = sub.add_parser("check", help="verify manifest, thumbs and markup agree")
    p_check.set_defaults(func=cmd_check)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
