#!/usr/bin/env python3
"""Keep the gallery manifest, its thumbnails and the grid markup in agreement.

The home page gallery used to be nineteen hand-written <button> elements
pointing straight at full-resolution originals -- so the grid downloaded
7.65 MB of images to display thumbnails. This tool owns that markup now.

  sync   rebuild thumbnails and the markup between the gallery:start and
         gallery:end markers in index.html from the manifest
  add    take one or more submitted photos, derive a web-sized original and a
         thumbnail, append manifest entries, then sync
  check  verify the manifest, the thumbnails and the markup all agree; exits
         non-zero on any drift, so CI can catch a photo added by hand

The tool only ever *appends* to the manifest, so comments and hand-written
notes in it survive. It never rewrites the file wholesale.

Requires PyYAML and Pillow.
"""

from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import re
import sys

import yaml
from PIL import Image, ImageOps

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "data" / "gallery.yml"
PHOTOS = ROOT / "assets" / "img" / "events"
THUMBS = PHOTOS / "thumbs"
INDEX = ROOT / "index.html"
# Deliberately not committed: the whole repository is published by GitHub
# Pages, so anything tracked here would be public. See README.
CONTACTS = ROOT / "submissions" / "contacts.yml"

START = "<!-- gallery:start -- generated by tools/gallery.py; do not edit by hand -->"
END = "<!-- gallery:end -->"

THUMB_EDGE = 480
THUMB_QUALITY = 78
FULL_EDGE = 1600
FULL_QUALITY = 82
INDENT = " " * 8


# ---------------------------------------------------------------- manifest --


def load() -> list[dict]:
    if not MANIFEST.exists():
        sys.exit(f"missing manifest: {MANIFEST.relative_to(ROOT)}")
    data = yaml.safe_load(MANIFEST.read_text()) or {}
    photos = data.get("photos") or []
    if not isinstance(photos, list):
        sys.exit("manifest: 'photos' must be a list")
    for entry in photos:
        if not isinstance(entry, dict) or not entry.get("file"):
            sys.exit(f"manifest: every entry needs a 'file' key (got {entry!r})")
    return photos


def append(entries: list[dict]) -> None:
    """Append entries as text so existing comments and ordering survive."""
    out = []
    for entry in entries:
        out.append(f"  - file: {json.dumps(entry['file'], ensure_ascii=False)}")
        out.append(f"    alt: {json.dumps(entry['alt'], ensure_ascii=False)}")
        for key in ("credit", "date"):
            if entry.get(key):
                out.append(f"    {key}: {json.dumps(entry[key], ensure_ascii=False)}")
    text = MANIFEST.read_text()
    if not text.endswith("\n"):
        text += "\n"
    MANIFEST.write_text(text + "\n".join(out) + "\n")


def remember_contact(name: str, email: str, files: list[str]) -> None:
    CONTACTS.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "date": datetime.date.today().isoformat(),
        "name": name,
        "email": email,
        "files": files,
    }
    with CONTACTS.open("a") as handle:
        handle.write(yaml.safe_dump([record], sort_keys=False, allow_unicode=True))


# -------------------------------------------------------------- derivatives --


def derive(src: pathlib.Path, dst: pathlib.Path, edge: int, quality: int) -> None:
    """Write a bounded, metadata-free copy of src to dst.

    Re-encoding through a fresh image drops ALL metadata, which is the point:
    phone photos carry GPS coordinates and we do not want to publish those.
    exif_transpose applies the orientation tag first so portrait shots do not
    come out sideways once that tag is gone.
    """
    with Image.open(src) as im:
        im = ImageOps.exif_transpose(im)
        im = im.convert("RGB")
        im.thumbnail((edge, edge * 4), Image.LANCZOS)
        dst.parent.mkdir(parents=True, exist_ok=True)
        im.save(dst, "JPEG", quality=quality, optimize=True, progressive=True)


def thumb_path(name: str) -> pathlib.Path:
    return THUMBS / (pathlib.Path(name).stem + ".jpg")


# ----------------------------------------------------------------- markup --


def render(photos: list[dict]) -> str:
    lines = []
    for entry in photos:
        name = entry["file"]
        src = f"assets/img/events/thumbs/{pathlib.Path(name).stem}.jpg"
        full = f"assets/img/events/{name}"
        alt = entry.get("alt", "")
        lines.append(
            f'{INDENT}<button type="button">'
            f'<img src="{src}" data-full="{full}" alt="{alt}"></button>'
        )
    return "\n".join(lines)


def splice(index_text: str, body: str) -> str:
    pattern = re.compile(
        re.escape(START) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(index_text):
        sys.exit(
            "index.html is missing the gallery markers -- expected\n"
            f"  {START}\n  {END}"
        )
    replacement = f"{START}\n{body}\n{INDENT}{END}"
    return pattern.sub(lambda _: replacement, index_text, count=1)


# ---------------------------------------------------------------- commands --


def cmd_sync(args) -> int:
    photos = load()
    for entry in photos:
        src = PHOTOS / entry["file"]
        if not src.exists():
            sys.exit(f"manifest lists a missing photo: {src.relative_to(ROOT)}")
        dst = thumb_path(entry["file"])
        if args.force or not dst.exists() or dst.stat().st_mtime < src.stat().st_mtime:
            derive(src, dst, THUMB_EDGE, THUMB_QUALITY)
    INDEX.write_text(splice(INDEX.read_text(), render(photos)))
    print(f"  {len(photos)} photos  ->  thumbs + index.html markup")
    return 0


def add_photos(files, *, alt: str, credit: str, date: str) -> list[dict]:
    """Derive web-sized copies, append manifest entries and sync.

    Shared by the `add` command and by tools/publish_submissions.py, which is
    what the publishing Action runs -- so a queued submission and a photo
    added by hand go through identical processing.
    """
    used = {entry["file"] for entry in load()}
    numbers = [
        int(p.stem) for p in PHOTOS.iterdir()
        if p.is_file() and p.stem.isdigit()
    ]
    nxt = max(numbers, default=0)
    added: list[dict] = []

    for raw in files:
        src = pathlib.Path(raw).expanduser()
        if not src.exists():
            raise SystemExit(f"no such file: {src}")
        nxt += 1
        name = f"{nxt:02d}.jpg"
        while name in used:
            nxt += 1
            name = f"{nxt:02d}.jpg"
        used.add(name)
        dst = PHOTOS / name
        derive(src, dst, FULL_EDGE, FULL_QUALITY)
        added.append({"file": name, "alt": alt, "credit": credit, "date": date})
        before = src.stat().st_size
        after = dst.stat().st_size
        print(
            f"  {src.name}  ->  {dst.relative_to(ROOT)}"
            f"  ({before / 1048576:.2f} MB -> {after / 1048576:.2f} MB, EXIF stripped)"
        )

    append(added)
    cmd_sync(argparse.Namespace(force=False))
    return added


def cmd_add(args) -> int:
    added = add_photos(
        args.files, alt=args.alt, credit=args.credit, date=args.date
    )
    if args.email:
        remember_contact(args.name or args.credit, args.email, [e["file"] for e in added])
        print(f"  contact recorded in {CONTACTS.relative_to(ROOT)} (not committed)")
    return 0


def cmd_check(args) -> int:
    photos = load()
    problems: list[str] = []

    for entry in photos:
        src = PHOTOS / entry["file"]
        if not src.exists():
            problems.append(f"manifest lists a missing photo: {entry['file']}")
        if not thumb_path(entry["file"]).exists():
            problems.append(f"missing thumbnail for {entry['file']} (run: gallery.py sync)")

    on_disk = {
        p.name for p in PHOTOS.iterdir()
        if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}
    }
    for name in sorted(on_disk - {e["file"] for e in photos}):
        problems.append(f"{name} is in assets/img/events/ but not in the manifest")

    index_text = INDEX.read_text()
    expected = splice(index_text, render(photos))
    if expected != index_text:
        problems.append("index.html gallery markup is out of date (run: gallery.py sync)")

    for problem in problems:
        print(f"  FAIL  {problem}")
    if problems:
        print(f"\n{len(problems)} problem(s)")
        return 1
    print(f"  OK  {len(photos)} photos, thumbs present, markup in sync")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_sync = sub.add_parser("sync", help="rebuild thumbs and markup from the manifest")
    p_sync.add_argument("--force", action="store_true", help="rebuild every thumb")
    p_sync.set_defaults(func=cmd_sync)

    p_add = sub.add_parser("add", help="add submitted photos and publish them")
    p_add.add_argument("files", nargs="+")
    p_add.add_argument("--alt", default="Photo from a previous SUAS event")
    p_add.add_argument("--credit", default="")
    p_add.add_argument("--date", default=datetime.date.today().isoformat())
    p_add.add_argument("--name", default="", help="submitter's name, for the contact log")
    p_add.add_argument("--email", default="", help="submitter's email, for the contact log")
    p_add.set_defaults(func=cmd_add)

    p_check = sub.add_parser("check", help="verify manifest, thumbs and markup agree")
    p_check.set_defaults(func=cmd_check)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
