#!/usr/bin/env python3
"""Keep the gallery manifests, their thumbnails and the markup in agreement.

The home page gallery used to be nineteen hand-written <button> elements
pointing straight at full-resolution originals -- so the grid downloaded
7.65 MB of images to display thumbnails. This tool owns that markup now.

There are two collections, each with its own manifest and its own page:

  gallery.yml      curated event photos -> the grid and hero slides on
                   index.html
  submissions.yml  whatever members have sent in through the upload form ->
                   the sideways rail on submit.html, which carries the
                   submitter's credit, caption and date into the lightbox

  sync   rebuild thumbnails, hero slides and the generated markup between
         the gallery:start / gallery:end, hero:start / hero:end and
         submissions:start / submissions:end markers
  add    take one or more newly supplied photos, derive a web-sized original
         and a thumbnail, append manifest entries, then sync
  check  verify each manifest, the thumbnails and the markup all agree; exits
         non-zero on any drift, so CI can catch a photo added by hand

  remove take a photo out of the gallery and off the served site: its manifest
         entry, its derivatives and its markup, in one step

The tool only ever *appends* to a manifest, so comments and hand-written
notes in it survive. It never rewrites a file wholesale, except when removing
an entry, which cannot be done any other way.

Requires PyYAML and Pillow.
"""

from __future__ import annotations

import argparse
import datetime
import html
import json
import pathlib
import re
import subprocess
import sys

import yaml
from PIL import Image, ImageOps

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "data" / "gallery.yml"
# Submitted photos live in the same directory and come out of the same
# processing as the curated ones; what separates them is the manifest they are
# listed in, and therefore which page they appear on.
SUBMISSION_MANIFEST = ROOT / "assets" / "data" / "submissions.yml"
PHOTOS = ROOT / "assets" / "img" / "events"
THUMBS = PHOTOS / "thumbs"
SLIDES = ROOT / "assets" / "img" / "hero-slides"
INDEX = ROOT / "index.html"
SUBMIT = ROOT / "submit.html"
# Submitter names and email addresses, and the record of what was removed and
# why. These are a LOCAL WORKING COPY: the site is published from this branch
# verbatim, so anything committed to main is public, and the one path that is
# provably not published is another branch. The publish workflow commits these
# to the `contacts` branch (see .github/workflows/publish-submission.yml), which
# Pages does not deploy, and never to main.
#
# The obvious alternative -- hiding them behind a dot-directory on main -- does
# not work and was tried: Pages serves .contacts/contacts.yml in plain text. It
# excludes .git and .github by name, not dot-directories as a class. Do not put
# a contact address back on main.
CONTACTS = ROOT / ".contacts" / "contacts.yml"

START = "<!-- gallery:start -- generated by tools/gallery.py; do not edit by hand -->"
END = "<!-- gallery:end -->"
# The home page hero band crossfades through the gallery photos. Its markup
# is generated from the same manifest into its own markers.
HERO_START = "<!-- hero:start -- generated by tools/gallery.py; do not edit by hand -->"
HERO_END = "<!-- hero:end -->"
# The submit page's own gallery: what members have sent in, kept off the home
# page so that it stays curated.
RAIL_START = "<!-- submissions:start -- generated by tools/gallery.py; do not edit by hand -->"
RAIL_END = "<!-- submissions:end -->"
# Shown inside the rail markers while nothing has been submitted yet.
RAIL_EMPTY = (
    '<p class="rail__empty">Nothing has been sent in yet &mdash; yours could be '
    "the first. Use the button above to add your photos to this gallery.</p>"
)

THUMB_EDGE = 480
THUMB_QUALITY = 78
FULL_EDGE = 1600
FULL_QUALITY = 82
SLIDE_EDGE = 1280
SLIDE_QUALITY = 80
INDENT = " " * 8
HERO_INDENT = " " * 4
# Every number the site has ever handed out, whatever extension, so that a
# number that has been taken down is never given to a different photo later.
# The site has photos predating this scheme that are not .jpg (03.png), and
# `remove` writes them back out, so the extension is not assumed anywhere.
NUMBERED = re.compile(r"^(\d+)\.[A-Za-z0-9]+$")
REMOVALS = ROOT / ".contacts" / "removals.yml"


# ---------------------------------------------------------------- manifest --


def load(path: pathlib.Path = MANIFEST) -> list[dict]:
    if not path.exists():
        sys.exit(f"missing manifest: {path.relative_to(ROOT)}")
    data = yaml.safe_load(path.read_text()) or {}
    photos = data.get("photos") or []
    if not isinstance(photos, list):
        sys.exit(f"{path.name}: 'photos' must be a list")
    for entry in photos:
        if not isinstance(entry, dict) or not entry.get("file"):
            sys.exit(f"{path.name}: every entry needs a 'file' key (got {entry!r})")
    return photos


def append(entries: list[dict], path: pathlib.Path = MANIFEST) -> None:
    """Append entries as text so existing comments and ordering survive."""
    out = []
    for entry in entries:
        out.append(f"  - file: {json.dumps(entry['file'], ensure_ascii=False)}")
        out.append(f"    alt: {json.dumps(entry['alt'], ensure_ascii=False)}")
        for key in ("credit", "caption", "date"):
            if entry.get(key):
                out.append(f"    {key}: {json.dumps(entry[key], ensure_ascii=False)}")
    text = path.read_text()
    if not text.endswith("\n"):
        text += "\n"
    # Appended entries are a block sequence, which an empty list written as
    # `photos: []` cannot take -- the file would stop parsing. Rewrite that
    # one form in passing, so the first append works whatever the manifest
    # looked like before it.
    text = re.sub(r"^photos:\s*\[\s*\]\s*$", "photos:", text, count=1, flags=re.MULTILINE)
    path.write_text(text + "\n".join(out) + "\n")


CONTACTS_HEADER = """\
# Who sent which photos, and how to reach them.
#
# For the committee, not for the public. This file lives on the `contacts`
# branch, which GitHub Pages does not deploy, so it is readable by anyone with
# access to the repository and served to nobody.
#
# It must never be committed to main. Everything on main is published, and
# Pages serves dot-directories like this one in plain text -- a dot-directory
# is not a hiding place.
#
# Appended by tools/gallery.py and tools/publish_submissions.py. Safe to edit by
# hand; the next append rewrites the file from this list.
"""


def used_numbers() -> set[int]:
    """Every number this site has ever used for a photo, in any of the three
    places a number can be recorded: on disk now, in the manifests, and in the
    git history.

    The history is the one that matters. A photo that has been removed is gone
    from disk and from its manifest, but the name it was published under is in
    the commit log for ever -- and if that number were handed to the next
    upload, a different photo would be served from a URL that search engines
    and people who shared the link have already cached against the photo that
    was taken down. So numbers are spent, permanently.
    """
    numbers = set()

    for entry in load() + load(SUBMISSION_MANIFEST):
        match = NUMBERED.match(pathlib.Path(str(entry.get("file", ""))).name)
        if match:
            numbers.add(int(match.group(1)))

    if PHOTOS.is_dir():
        for path in PHOTOS.iterdir():
            if path.is_file():
                match = NUMBERED.match(path.name)
                if match:
                    numbers.add(int(match.group(1)))

    # History is best-effort: a tarball export, a fresh clone, or a CI runner
    # with a shallow checkout must not be able to stop a photo being added.
    try:
        log = subprocess.run(
            ["git", "log", "--all", "--name-only", "--pretty=format:",
             "--", str(PHOTOS.relative_to(ROOT))],
            cwd=ROOT, capture_output=True, text=True, timeout=30, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return numbers
    prefix = f"{PHOTOS.relative_to(ROOT).as_posix()}/"
    for line in log.stdout.splitlines():
        name = line.strip()
        if not name.startswith(prefix):
            continue
        match = NUMBERED.match(name[len(prefix):])
        if match:
            numbers.add(int(match.group(1)))
    return numbers


def remember_contact(
    name: str, email: str, files: list[str], *, date: str = "", credit: str = ""
) -> None:
    """Record a submitter's name and email beside the files they sent.

    Read-then-rewrite rather than append: a second top-level YAML sequence
    would not parse, so the file was previously only ever safe to read with
    your eyes. It is small and rewritten on every upload, so correctness
    beats append-only here.
    """
    if not email:
        return
    record = {"date": date or datetime.date.today().isoformat()}
    if name:
        record["name"] = name
    if credit:
        record["credit"] = credit
    record["email"] = email
    record["files"] = list(files)

    CONTACTS.parent.mkdir(parents=True, exist_ok=True)
    records: list = []
    if CONTACTS.exists():
        try:
            loaded = yaml.safe_load(CONTACTS.read_text()) or []
        except yaml.YAMLError:
            loaded = []
        if isinstance(loaded, list):
            records = loaded
    records.append(record)
    CONTACTS.write_text(
        CONTACTS_HEADER + yaml.safe_dump(records, sort_keys=False, allow_unicode=True)
    )


# -------------------------------------------------------------- derivatives --


def derive(src: pathlib.Path, dst: pathlib.Path, edge: int, quality: int) -> None:
    """Write a bounded, metadata-free copy of src to dst.

    Re-encoding through a fresh image drops ALL metadata, which is the point:
    phone photos carry GPS coordinates and we do not want to publish those.
    exif_transpose applies the orientation tag first so portrait shots do not
    come out sideways once that tag is gone.
    """
    with Image.open(src) as im:
        im = ImageOps.exif_transpose(im)
        im = im.convert("RGB")
        im.thumbnail((edge, edge * 4), Image.LANCZOS)
        dst.parent.mkdir(parents=True, exist_ok=True)
        im.save(dst, "JPEG", quality=quality, optimize=True, progressive=True)


def thumb_path(name: str) -> pathlib.Path:
    return THUMBS / (pathlib.Path(name).stem + ".jpg")


def slide_path(name: str) -> pathlib.Path:
    return SLIDES / (pathlib.Path(name).stem + ".jpg")


# ----------------------------------------------------------------- markup --


def attr(value) -> str:
    """An attribute value, safely quoted.

    Captions and credits are written by members rather than by us, so they are
    the one thing in the generated markup that cannot be assumed markup-free.
    Newlines and runs of spaces are collapsed too: a caption is a sentence,
    not a layout.
    """
    return html.escape(" ".join(str(value or "").split()), quote=True)


def render(photos: list[dict]) -> str:
    lines = []
    for entry in photos:
        name = entry["file"]
        src = f"assets/img/events/thumbs/{pathlib.Path(name).stem}.jpg"
        full = f"assets/img/events/{name}"
        lines.append(
            f'{INDENT}<button type="button">'
            f'<img src="{src}" data-full="{attr(full)}"'
            f' alt="{attr(entry.get("alt", ""))}"></button>'
        )
    return "\n".join(lines)


def render_rail(photos: list[dict]) -> str:
    """The submit page's own gallery: one button per submitted photo.

    Each button carries the submission's details as data attributes, which is
    what the lightbox reads to show who sent the photo and what they said
    about it. Nothing is served for them separately -- the details travel with
    the image they belong to.
    """
    if not photos:
        return INDENT + RAIL_EMPTY
    lines = []
    for entry in photos:
        stem = pathlib.Path(entry["file"]).stem
        src = f"assets/img/events/thumbs/{stem}.jpg"
        full = f"assets/img/events/{entry['file']}"
        bits = [f'src="{attr(src)}"', f'data-full="{attr(full)}"']
        for key in ("credit", "caption", "date"):
            if entry.get(key):
                bits.append(f'data-{key}="{attr(entry[key])}"')
        bits.append(f'alt="{attr(entry.get("alt", ""))}"')
        lines.append(
            f'{INDENT}<button type="button" class="rail__item">'
            f'<img {" ".join(bits)}></button>'
        )
    return "\n".join(lines)


def splice(index_text: str, body: str, start: str = START, end: str = END,
           indent: str = INDENT) -> str:
    pattern = re.compile(
        re.escape(start) + r".*?" + re.escape(end), re.DOTALL
    )
    if not pattern.search(index_text):
        sys.exit(
            "the page is missing the markers this markup is generated into --\n"
            f"expected to find both of:\n  {start}\n  {end}"
        )
    replacement = f"{start}\n{body}\n{indent}{end}"
    return pattern.sub(lambda _: replacement, index_text, count=1)


# ------------------------------------------------------------------- hero --


def render_hero(photos: list[dict]) -> str:
    """The hero band's crossfading slides: one <figure> per gallery photo.

    Slides reuse the 480 px grid thumbnails on small screens via srcset and
    load a 1280 px derivative the rest of the time. Only the first slide is
    eager; the rest are lazy, so nothing above the fold waits on them and
    the show pulls images one at a time as it advances. The first figure
    carries is-current in the markup, which is what a no-JS visitor sees.
    """
    lines = []
    for i, entry in enumerate(photos):
        stem = pathlib.Path(entry["file"]).stem
        slide = f"assets/img/hero-slides/{stem}.jpg"
        thumb = f"assets/img/events/thumbs/{stem}.jpg"
        alt = entry.get("alt", "")
        loading = "eager" if i == 0 else "lazy"
        current = " is-current" if i == 0 else ""
        lines.append(
            f'{HERO_INDENT}<figure class="hero__slide{current}">'
            f'<img src="{slide}" srcset="{thumb} 480w, {slide} 1280w"'
            f' sizes="100vw" loading="{loading}" alt="{alt}"></figure>'
        )
    return "\n".join(lines)


def splice_hero(index_text: str, body: str) -> str:
    return splice(index_text, body, HERO_START, HERO_END, HERO_INDENT)


def splice_rail(submit_text: str, body: str) -> str:
    return splice(submit_text, body, RAIL_START, RAIL_END)


# ---------------------------------------------------------------- commands --


def refresh(entry: dict, *, slides: bool, force: bool = False) -> None:
    """Re-derive the sizes this photo needs, where a derivative is stale."""
    src = PHOTOS / entry["file"]
    if not src.exists():
        sys.exit(f"manifest lists a missing photo: {src.relative_to(ROOT)}")
    wanted = [(thumb_path(entry["file"]), THUMB_EDGE, THUMB_QUALITY)]
    if slides:
        wanted.append((slide_path(entry["file"]), SLIDE_EDGE, SLIDE_QUALITY))
    for dst, edge, quality in wanted:
        if force or not dst.exists() or dst.stat().st_mtime < src.stat().st_mtime:
            derive(src, dst, edge, quality)


def cmd_sync(args) -> int:
    curated = load()
    sent_in = load(SUBMISSION_MANIFEST)
    for entry in curated:
        refresh(entry, slides=True, force=args.force)
    for entry in sent_in:
        # Submitted photos are not on the home page, so they get no hero slide.
        refresh(entry, slides=False, force=args.force)

    index = INDEX.read_text()
    index = splice(index, render(curated))
    index = splice_hero(index, render_hero(curated))
    INDEX.write_text(index)

    submit = SUBMIT.read_text()
    SUBMIT.write_text(splice_rail(submit, render_rail(sent_in)))

    print(f"  {len(curated)} home-page photos  ->  thumbs, hero slides + index.html markup")
    print(f"  {len(sent_in)} submitted photos  ->  thumbs + submit.html markup")
    return 0


def add_photos(
    files,
    *,
    alt: str,
    credit: str,
    date: str,
    caption: str = "",
    collection: str = "gallery",
) -> list[dict]:
    """Derive web-sized copies, append manifest entries and sync.

    Shared by the `add` command and by tools/publish_submissions.py, which is
    what the publishing Action runs -- so a queued submission and a photo
    added by hand go through identical processing. `collection` decides which
    manifest the entries land in, and therefore which page shows them; the
    file numbering is shared, so a photo only ever has one name.
    """
    to_submissions = collection == "submissions"
    manifest = SUBMISSION_MANIFEST if to_submissions else MANIFEST
    used = {entry["file"] for entry in load() + load(SUBMISSION_MANIFEST)}
    # Spent numbers included, so a number freed by a takedown is never handed
    # to a different photo at a URL that is already cached against the old one.
    nxt = max(used_numbers(), default=0)
    added: list[dict] = []

    for raw in files:
        src = pathlib.Path(raw).expanduser()
        if not src.exists():
            raise SystemExit(f"no such file: {src}")
        nxt += 1
        name = f"{nxt:02d}.jpg"
        while name in used:
            nxt += 1
            name = f"{nxt:02d}.jpg"
        used.add(name)
        dst = PHOTOS / name
        derive(src, dst, FULL_EDGE, FULL_QUALITY)
        if not to_submissions:
            derive(src, slide_path(name), SLIDE_EDGE, SLIDE_QUALITY)
        added.append(
            {
                "file": name,
                "alt": alt,
                "credit": credit,
                "caption": caption,
                "date": date,
            }
        )
        before = src.stat().st_size
        after = dst.stat().st_size
        print(
            f"  {src.name}  ->  {dst.relative_to(ROOT)}"
            f"  ({before / 1048576:.2f} MB -> {after / 1048576:.2f} MB, EXIF stripped)"
        )

    append(added, manifest)
    cmd_sync(argparse.Namespace(force=False))
    return added


def record_removal(name: str, *, credit: str, reason: str, manifest: str) -> None:
    """Note a takedown in a file the repository publishes nowhere.

    The site promises photos can be taken down again on request, which makes
    this a consent-withdrawal record rather than housekeeping: being able to
    show what was removed, by whom and why is the part that actually protects
    the society. Lives on the `contacts` branch with the contact log, which
    Pages does not deploy.
    """
    record = {
        "date": datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
        "file": name,
        "credit": credit,
        "reason": reason,
        "removed_from": manifest,
    }
    REMOVALS.parent.mkdir(parents=True, exist_ok=True)
    header = ""
    if not REMOVALS.exists():
        header = (
            "# Photos taken out of the gallery, and why.\n"
            "#\n"
            "# Written by tools/gallery.py remove, and committed to the `contacts`\n"
            "# branch, which GitHub Pages does not deploy. Never commit this to\n"
            "# main: everything on main is served.\n"
            "#\n"
            "# This is the record for a takedown asked for on request. It does not\n"
            "# mean the photo is unrecoverable -- the bytes stay in git history and\n"
            "# in web archives. See relay/README.md for the follow-up that needs.\n\n"
        )
    records: list = []
    if REMOVALS.exists():
        try:
            loaded = yaml.safe_load(REMOVALS.read_text()) or []
        except yaml.YAMLError:
            loaded = []
        if isinstance(loaded, list):
            records = loaded
    records.append(record)
    REMOVALS.write_text(
        header + yaml.safe_dump(records, sort_keys=False, allow_unicode=True)
    )


def remove_photos(name: str, *, reason: str = "") -> dict | None:
    """Take one photo out of the gallery and off the served site.

    Unlisting and purging are one operation here on purpose. Either alone is
    wrong: leave the file and the URL keeps serving the photo even though
    nothing links to it, and leave the manifest entry and `check` fails
    because the file has no entry. Deleting a photo is a consent question
    often enough that a half-done takedown is the worst outcome available, so
    there is no way to do half of it.

    Returns what was removed, or None if no manifest listed the photo.
    """
    # Accept a bare number, a filename, or a path, since all three are things a
    # person reading the rail, a URL, or a screenshot will have to hand. Matched
    # on the stem rather than the whole name so that a bare "22" finds 22.jpg
    # and "03" finds 03.png -- the extension belongs to the manifest, which is
    # what decides the answer, and the gallery is not all .jpg.
    raw = pathlib.Path(str(name).strip()).name
    stem = raw.split(".")[0] if NUMBERED.match(raw) else raw

    def is_target(entry) -> bool:
        listed = pathlib.Path(str(entry.get("file", ""))).name
        return listed == raw or (
            NUMBERED.match(listed) and listed.split(".")[0] == stem
        )

    # Which manifest it is in decides which page it appears on, and the home
    # page is a curated gallery we do not want an id-driven path rewriting.
    # Both are handled, but only the submitted one is reachable from the site.
    found = None
    for manifest, photos in (
        (SUBMISSION_MANIFEST, load(SUBMISSION_MANIFEST)),
        (MANIFEST, load()),
    ):
        for entry in photos:
            if is_target(entry):
                found = (manifest, entry)
                break
        if found:
            break

    if not found:
        return None

    manifest, entry = found
    # The manifest's own spelling, so the file we delete is the file it named.
    bare = pathlib.Path(str(entry["file"])).name
    targets = [
        PHOTOS / bare,
        thumb_path(bare),
        # A submitted photo never gets a hero slide, but a photo moved to the
        # curated manifest by hand does, and leaving that behind would be an
        # orphan that `check` fails on.
        slide_path(bare),
    ]
    removed_files = []
    for path in targets:
        if path.exists():
            path.unlink()
            removed_files.append(path.relative_to(ROOT).as_posix())

    drop_manifest_entry(manifest, bare)
    removed = {
        "file": bare,
        "credit": str(entry.get("credit") or ""),
        "files": removed_files,
        "manifest": manifest.relative_to(ROOT).as_posix(),
    }
    record_removal(
        bare,
        credit=removed["credit"],
        reason=reason,
        manifest=removed["manifest"],
    )
    return removed


def drop_manifest_entry(manifest: pathlib.Path, name: str) -> None:
    """Rewrite a manifest without one entry.

    This is the one place the tool rewrites a manifest wholesale, which the
    append-only rule otherwise exists to prevent. Removing an entry cannot be
    expressed as an append, and a photo that has been taken down should not
    keep its hand-written notes above it in the file either.
    """
    text = manifest.read_text()
    data = yaml.safe_load(text) or {}
    photos = data.get("photos") or []
    kept = [
        entry for entry in photos
        if pathlib.Path(str(entry.get("file", ""))).name != name
    ]
    if len(kept) == len(photos):
        return

    lines = []
    for entry in kept:
        lines.append(f"  - file: {json.dumps(entry['file'], ensure_ascii=False)}")
        if entry.get("alt"):
            lines.append(f"    alt: {json.dumps(entry['alt'], ensure_ascii=False)}")
        for key in ("credit", "caption", "date"):
            if entry.get(key):
                lines.append(f"    {key}: {json.dumps(entry[key], ensure_ascii=False)}")
    block = "photos:\n" + "\n".join(lines) + "\n" if kept else "photos: []\n"

    # Keep the file's leading comment block: it is the documentation for the
    # whole manifest and is the part no one wants to lose to a takedown.
    head = []
    for line in text.splitlines():
        if line.startswith("photos:"):
            break
        head.append(line)
    while head and not head[-1].strip():
        head.pop()
    manifest.write_text("\n".join(head) + "\n\n" + block)


def cmd_remove(args) -> int:
    removed = remove_photos(args.name, reason=args.reason or "")
    if not removed:
        sys.exit(
            f"no manifest lists {args.name!r} -- nothing to remove. "
            "Pass the number or filename, e.g. `gallery.py remove 22.jpg`."
        )
    print(f"  removed {removed['file']} from {removed['manifest']}")
    for path in removed["files"]:
        print(f"    deleted {path}")
    print(f"  noted in {REMOVALS.relative_to(ROOT)} (not published)")
    cmd_sync(argparse.Namespace(force=False))
    return 0


def cmd_add(args) -> int:
    added = add_photos(
        args.files,
        alt=args.alt,
        credit=args.credit,
        date=args.date,
        caption=args.caption,
        collection=args.collection,
    )
    if args.email:
        remember_contact(
            args.name or args.credit,
            args.email,
            [e["file"] for e in added],
            date=args.date,
            credit=args.credit,
        )
        print(
            f"  contact recorded in {CONTACTS.relative_to(ROOT)}"
            " (published to the contacts branch, not to the site)"
        )
    return 0


def collection_problems(entry: dict, *, slides: bool) -> list[str]:
    name = entry["file"]
    problems = []
    if not (PHOTOS / name).exists():
        problems.append(f"manifest lists a missing photo: {name}")
    if not thumb_path(name).exists():
        problems.append(f"missing thumbnail for {name} (run: gallery.py sync)")
    if slides and not slide_path(name).exists():
        problems.append(f"missing hero slide for {name} (run: gallery.py sync)")
    return problems


def cmd_check(args) -> int:
    curated = load()
    sent_in = load(SUBMISSION_MANIFEST)
    problems: list[str] = []

    for entry in curated:
        problems.extend(collection_problems(entry, slides=True))
    for entry in sent_in:
        problems.extend(collection_problems(entry, slides=False))

    on_disk = {
        p.name for p in PHOTOS.iterdir()
        if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}
    }
    listed = {e["file"] for e in curated} | {e["file"] for e in sent_in}
    for name in sorted(on_disk - listed):
        problems.append(f"{name} is in assets/img/events/ but in neither manifest")
    for name in sorted({e["file"] for e in curated} & {e["file"] for e in sent_in}):
        problems.append(f"{name} is listed in both manifests")

    # A number that is on disk must be the highest one handed out, and the next
    # one must be clear of every number ever spent. If a takedown ever freed a
    # number for reuse, this is where it shows up -- as the next number the
    # tool would pick already having a file under it.
    spent = used_numbers()
    on_disk = {p.name for p in PHOTOS.iterdir() if p.is_file()} if PHOTOS.is_dir() else set()
    nxt = f"{max(spent, default=0) + 1:02d}.jpg"
    if nxt in on_disk:
        problems.append(
            f"the next photo would be {nxt}, which is already on disk -- a removed "
            "number has been reused and would serve a different photo from a URL "
            "cached against the old one"
        )

    index_text = INDEX.read_text()
    expected = splice(index_text, render(curated))
    expected = splice_hero(expected, render_hero(curated))
    if expected != index_text:
        problems.append("index.html generated markup is out of date (run: gallery.py sync)")

    submit_text = SUBMIT.read_text()
    if splice_rail(submit_text, render_rail(sent_in)) != submit_text:
        problems.append("submit.html generated markup is out of date (run: gallery.py sync)")

    for problem in problems:
        print(f"  FAIL  {problem}")
    if problems:
        print(f"\n{len(problems)} problem(s)")
        return 1
    print(
        f"  OK  {len(curated)} home-page photos and {len(sent_in)} submitted, "
        "thumbs present, markup in sync"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_sync = sub.add_parser("sync", help="rebuild thumbs and markup from the manifest")
    p_sync.add_argument("--force", action="store_true", help="rebuild every thumb")
    p_sync.set_defaults(func=cmd_sync)

    p_add = sub.add_parser("add", help="add newly supplied photos and publish them")
    p_add.add_argument("files", nargs="+")
    p_add.add_argument("--alt", default="Photo from a previous SUAS event")
    p_add.add_argument("--credit", default="")
    p_add.add_argument("--caption", default="", help="shown with the photo on submit.html")
    p_add.add_argument(
        "--collection",
        choices=("gallery", "submissions"),
        default="gallery",
        help="which manifest and page the photos belong to",
    )
    p_add.add_argument("--date", default=datetime.date.today().isoformat())
    p_add.add_argument("--name", default="", help="submitter's name, for the contact log")
    p_add.add_argument("--email", default="", help="submitter's email, for the contact log")
    p_add.set_defaults(func=cmd_add)

    p_check = sub.add_parser("check", help="verify manifest, thumbs and markup agree")
    p_check.set_defaults(func=cmd_check)

    p_rm = sub.add_parser(
        "remove", help="take a photo out of the gallery and off the served site"
    )
    p_rm.add_argument("name", help="the number or filename, e.g. 22 or 22.jpg")
    p_rm.add_argument(
        "--reason",
        default="",
        help="why, recorded in .contacts/removals.yml",
    )
    p_rm.set_defaults(func=cmd_remove)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
